if(${MCU_NAME} MATCHES "^STM32WL33C8$|^STM32WL33CB$|^STM32WL33CC$|^STM32WL33K8$|^STM32WL33KB$|^STM32WL33KC$")
    set(i2c_subimplementation "${CMAKE_CURRENT_LIST_DIR}/hal_ll_i2c_master.c")
    set(rcc_subimplementation "${CMAKE_CURRENT_SOURCE_DIR}/../../include/rcc/implementations/doc_ds_190")
    set(gpio_subimplementation_include_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../include/gpio/implementations/doc_ds_190")
    list(APPEND hal_ll_def_list "STM32WLxx")
    list(APPEND hal_ll_def_list "STM32WL3xx")
    list(APPEND hal_ll_def_list "STM32WL33xx")
    set(i2c_pin_map "${CMAKE_CURRENT_SOURCE_DIR}/../../include/i2c/hal_ll_i2c_pin_map/implementations/doc_ds_190")
endif()
