if(${MCU_NAME} MATCHES "^STM32F405RG$|^STM32F405VG$|^STM32F405ZG$|^STM32F405OG$|^STM32F405OE$|^STM32F407VG$|^STM32F407IG$|^STM32F407ZG$|^STM32F407VE$|^STM32F407ZE$|^STM32F407IE$")
    set(spi_subimplementation "${CMAKE_CURRENT_LIST_DIR}/hal_ll_spi_master.c")
    set(rcc_subimplementation "${CMAKE_CURRENT_SOURCE_DIR}/../../include/rcc/implementations/doc_ds_48")
    set(gpio_subimplementation_include_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../include/gpio/implementations/doc_ds_48")
    list(APPEND hal_ll_def_list "STM32F4xx")
    list(APPEND hal_ll_def_list "STM32F40xx")
    list(APPEND hal_ll_def_list "STM32F405xx")
    set(spi_pin_map "${CMAKE_CURRENT_SOURCE_DIR}/../../include/spi_master/hal_ll_spi_master_pin_map/implementations/doc_ds_48")
endif()
