if(${MCU_NAME} MATCHES "^STM32U5A5AJ$|^STM32U5A5QI$|^STM32U5A5QJ$|^STM32U5A5RJ$|^STM32U5A5VJ$|^STM32U5A5ZJ$|^STM32U5A9BJ$|^STM32U5A9NJ$|^STM32U5A9VJ$|^STM32U5A9ZJ$")
    set(i2c_subimplementation "${CMAKE_CURRENT_LIST_DIR}/hal_ll_i2c_master.c")
    set(rcc_subimplementation "${CMAKE_CURRENT_SOURCE_DIR}/../../include/rcc/implementations/doc_ds_183")
    set(gpio_subimplementation_include_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../include/gpio/implementations/doc_ds_183")
    list(APPEND hal_ll_def_list "STM32U5xx")
    list(APPEND hal_ll_def_list "STM32U5Axx")
    list(APPEND hal_ll_def_list "STM32U5A5xx")
    set(i2c_pin_map "${CMAKE_CURRENT_SOURCE_DIR}/../../include/i2c/hal_ll_i2c_pin_map/implementations/doc_ds_183")
endif()
