if(${MCU_NAME} MATCHES "^STM32U083KC$|^STM32U083HC$|^STM32U083CC$|^STM32U083RC$|^STM32U083MC$")
    set(adc_subimplementation "${CMAKE_CURRENT_LIST_DIR}/hal_ll_adc.c")
    set(rcc_subimplementation "${CMAKE_CURRENT_SOURCE_DIR}/../../include/rcc/implementations/doc_ds_196")
    set(gpio_subimplementation_include_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../include/gpio/implementations/doc_ds_196")
    list(APPEND hal_ll_def_list "STM32U0xx")
    list(APPEND hal_ll_def_list "STM32U08xx")
    list(APPEND hal_ll_def_list "STM32U083xx")
    set(adc_pin_map "${CMAKE_CURRENT_SOURCE_DIR}/../../include/adc/hal_ll_adc_pin_map/implementations/doc_ds_196")
    list(APPEND hal_ll_def_list "HAL_LL_ADC_RESOLUTION_CMAKE=HAL_LL_ADC_RESOLUTION_12_BIT")
endif()
