if(${MCU_NAME} MATCHES "^R7F100GCF$|^R7F100GCG$|^R7F100GCH$|^R7F100GCJ$|^R7F100GEF$|^R7F100GEG$|^R7F100GEH$|^R7F100GEJ$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.S PARENT_SCOPE)
    list(APPEND local_list_include system/src/${vendor}/r7f100gce/init_clock.c system/src/${vendor}/r7f100gce/vectors.c)
    list(APPEND local_dir_install system/src/${vendor}/r7f100gce)
    set(${thirdpartyInstall} "r7f100gce" PARENT_SCOPE)
endif()
