if(${MCU_NAME} MATCHES "^R7F100GMG$|^R7F100GMH$|^R7F100GMJ$|^R7F100GMK$|^R7F100GML$|^R7F100GMN$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.S PARENT_SCOPE)
    list(APPEND local_list_include system/src/${vendor}/r7f100gm/init_clock.c system/src/${vendor}/r7f100gm/vectors.c)
    list(APPEND local_dir_install system/src/${vendor}/r7f100gm)
    set(${thirdpartyInstall} "r7f100gm" PARENT_SCOPE)
endif()
