if(${MCU_NAME} MATCHES "^R7F100GPG$|^R7F100GPH$|^R7F100GPJ$|^R7F100GPK$|^R7F100GPL$|^R7F100GPN$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.S PARENT_SCOPE)
    list(APPEND local_list_include system/src/${vendor}/r7f100gp/init_clock.c system/src/${vendor}/r7f100gp/vectors.c)
    list(APPEND local_dir_install system/src/${vendor}/r7f100gp)
    set(${thirdpartyInstall} "r7f100gp" PARENT_SCOPE)
endif()
