if(${MCU_NAME} MATCHES "^R7F100GSJ$|^R7F100GSK$|^R7F100GSL$|^R7F100GSN$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.S PARENT_SCOPE)
    list(APPEND local_list_include system/src/${vendor}/r7f100gs/init_clock.c system/src/${vendor}/r7f100gs/vectors.c)
    list(APPEND local_dir_install system/src/${vendor}/r7f100gs)
    set(${thirdpartyInstall} "r7f100gs" PARENT_SCOPE)
endif()
