if(${MCU_NAME} MATCHES "^STM32L552CC$|^STM32L552CE$|^STM32L552ME$|^STM32L552QC$|^STM32L552QE$|^STM32L552RC$|^STM32L552RE$|^STM32L552VC$|^STM32L552VE$|^STM32L552ZC$|^STM32L552ZE$")
    set(adc_subimplementation "${CMAKE_CURRENT_LIST_DIR}/hal_ll_adc.c")
    set(rcc_subimplementation "${CMAKE_CURRENT_SOURCE_DIR}/../../include/rcc/implementations/doc_ds_164")
    set(gpio_subimplementation_include_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../include/gpio/implementations/doc_ds_164")
    list(APPEND hal_ll_def_list "STM32L5xx")
    list(APPEND hal_ll_def_list "STM32L55xx")
    list(APPEND hal_ll_def_list "STM32L552xx")
    set(adc_pin_map "${CMAKE_CURRENT_SOURCE_DIR}/../../include/adc/hal_ll_adc_pin_map/implementations/doc_ds_164")
    list(APPEND hal_ll_def_list "HAL_LL_ADC_RESOLUTION_CMAKE=HAL_LL_ADC_RESOLUTION_12_BIT")
endif()
