if(${MCU_NAME} MATCHES "^STM32H7S3A8$|^STM32H7S3I8$|^STM32H7S3L8$|^STM32H7S3R8$|^STM32H7S3V8$|^STM32H7S3Z8$|^STM32H7S7A8$|^STM32H7S7I8$|^STM32H7S7L8$|^STM32H7S7Z8$")
    set(adc_subimplementation "${CMAKE_CURRENT_LIST_DIR}/hal_ll_adc.c")
    set(rcc_subimplementation "${CMAKE_CURRENT_SOURCE_DIR}/../../include/rcc/implementations/doc_ds_193")
    set(gpio_subimplementation_include_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../include/gpio/implementations/doc_ds_193")
    list(APPEND hal_ll_def_list "STM32H7xx")
    list(APPEND hal_ll_def_list "STM32H7Sxx")
    list(APPEND hal_ll_def_list "STM32H7S3xx")
    set(adc_pin_map "${CMAKE_CURRENT_SOURCE_DIR}/../../include/adc/hal_ll_adc_pin_map/implementations/doc_ds_193")
    list(APPEND hal_ll_def_list "HAL_LL_ADC_RESOLUTION_CMAKE=HAL_LL_ADC_RESOLUTION_12_BIT")
endif()
