if(${MCU_NAME} MATCHES "^STM32F405RG$|^STM32F405VG$|^STM32F405ZG$|^STM32F405OG$|^STM32F405OE$|^STM32F407VG$|^STM32F407IG$|^STM32F407ZG$|^STM32F407VE$|^STM32F407ZE$|^STM32F407IE$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.s PARENT_SCOPE)
    list(APPEND local_list_include system/src/stm/doc_ds_48/init_clock.c)
    list(APPEND local_list_include system/src/stm/doc_ds_48/thirdparty/Src/system_stm32f4xx.c)
    list(APPEND local_list_include system/src/stm/doc_ds_48/thirdparty/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_48/thirdparty/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c)
    list(APPEND local_list_include system/src/stm/doc_ds_48/thirdparty/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_48/thirdparty/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c)
endif()
