if(${MCU_NAME} MATCHES "^STM32WLE5C8$|^STM32WLE5CB$|^STM32WLE5CC$|^STM32WLE5J8$|^STM32WLE5JB$|^STM32WLE5JC$|^STM32WLE4C8$|^STM32WLE4CB$|^STM32WLE4CC$|^STM32WLE4J8$|^STM32WLE4JB$|^STM32WLE4JC$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.s PARENT_SCOPE)
    list(APPEND local_list_include system/src/stm/doc_ds_192/init_clock.c)
    list(APPEND local_list_include system/src/stm/doc_ds_192/thirdparty/Src/system_stm32wlxx.c)
    list(APPEND local_list_include system/src/stm/doc_ds_192/thirdparty/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cortex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_192/thirdparty/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal.c)
    list(APPEND local_list_include system/src/stm/doc_ds_192/thirdparty/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr_ex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_192/thirdparty/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc.c)
endif()
