if(${MCU_NAME} MATCHES "^STM32H503EB$|^STM32H503KB$|^STM32H503CB$|^STM32H503RB$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.s PARENT_SCOPE)
    list(APPEND local_list_include system/src/stm/doc_ds_90/init_clock.c)
    list(APPEND local_list_include system/src/stm/doc_ds_90/thirdparty/Src/system_stm32h5xx.c)
    list(APPEND local_list_include system/src/stm/doc_ds_90/thirdparty/Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal.c)
    list(APPEND local_list_include system/src/stm/doc_ds_90/thirdparty/Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_rcc.c)
    list(APPEND local_list_include system/src/stm/doc_ds_90/thirdparty/Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_cortex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_90/thirdparty/Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_pwr_ex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_90/thirdparty/Drivers/CMSIS/Device/ST/STM32H5xx/Source/Templates/system_stm32h5xx_ns.c)
    list(APPEND local_list_include system/src/stm/doc_ds_90/thirdparty/Drivers/CMSIS/Device/ST/STM32H5xx/Source/Templates/system_stm32h5xx_s.c)
endif()
