if(${MCU_NAME} MATCHES "^STM32H7B3RI$|^STM32H7B3VI$|^STM32H7B3QI$|^STM32H7B3ZI$|^STM32H7B3AI$|^STM32H7B3II$|^STM32H7B3NI$|^STM32H7B3LI$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.s PARENT_SCOPE)
    list(APPEND local_list_include system/src/stm/doc_ds_107/init_clock.c)
    list(APPEND local_list_include system/src/stm/doc_ds_107/thirdparty/Src/system_stm32h7xx.c)
    list(APPEND local_list_include system/src/stm/doc_ds_107/thirdparty/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_107/thirdparty/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_107/thirdparty/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c)
    list(APPEND local_list_include system/src/stm/doc_ds_107/thirdparty/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c)
    list(APPEND local_list_include system/src/stm/doc_ds_107/thirdparty/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/system_stm32h7xx_single)
    list(APPEND local_list_include system/src/stm/doc_ds_107/thirdparty/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/system_stm32h7xx_dual)
    list(APPEND local_list_include system/src/stm/doc_ds_107/thirdparty/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/system_stm32h7xx_dual)
    list(APPEND local_list_include system/src/stm/doc_ds_107/thirdparty/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/system_stm32h7xx_dual)
endif()
