if(${MCU_NAME} MATCHES "^STM32H735AG$|^STM32H735IG$|^STM32H735RG$|^STM32H735VG$|^STM32H735ZG$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.s PARENT_SCOPE)
    list(APPEND local_list_include system/src/stm/doc_ds_97/init_clock.c)
    list(APPEND local_list_include system/src/stm/doc_ds_97/thirdparty/Src/system_stm32h7xx.c)
    list(APPEND local_list_include system/src/stm/doc_ds_97/thirdparty/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_97/thirdparty/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_97/thirdparty/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c)
    list(APPEND local_list_include system/src/stm/doc_ds_97/thirdparty/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c)
    list(APPEND local_list_include system/src/stm/doc_ds_97/thirdparty/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/system_stm32h7xx_single)
    list(APPEND local_list_include system/src/stm/doc_ds_97/thirdparty/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/system_stm32h7xx_dual)
    list(APPEND local_list_include system/src/stm/doc_ds_97/thirdparty/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/system_stm32h7xx_dual)
    list(APPEND local_list_include system/src/stm/doc_ds_97/thirdparty/Drivers/CMSIS/Device/ST/STM32H7xx/Source/Templates/system_stm32h7xx_dual)
endif()
