if(${MCU_NAME} MATCHES "^STM32U545CE$|^STM32U545JE$|^STM32U545NE$|^STM32U545RE$|^STM32U545VE$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.s PARENT_SCOPE)
    list(APPEND local_list_include system/src/stm/doc_ds_179/init_clock.c)
    list(APPEND local_list_include system/src/stm/doc_ds_179/thirdparty/Src/system_stm32u5xx.c)
    list(APPEND local_list_include system/src/stm/doc_ds_179/thirdparty/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_pwr_ex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_179/thirdparty/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_rcc.c)
    list(APPEND local_list_include system/src/stm/doc_ds_179/thirdparty/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal_cortex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_179/thirdparty/Drivers/STM32U5xx_HAL_Driver/Src/stm32u5xx_hal.c)
    list(APPEND local_list_include system/src/stm/doc_ds_179/thirdparty/Drivers/CMSIS/Device/ST/STM32U5xx/Source/Templates/system_stm32u5xx_s.c)
    list(APPEND local_list_include system/src/stm/doc_ds_179/thirdparty/Drivers/CMSIS/Device/ST/STM32U5xx/Source/Templates/system_stm32u5xx_ns.c)
endif()
