if(${MCU_NAME} MATCHES "^STM32U083KC$|^STM32U083HC$|^STM32U083CC$|^STM32U083RC$|^STM32U083MC$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.s PARENT_SCOPE)
    list(APPEND local_list_include system/src/stm/doc_ds_196/init_clock.c)
    list(APPEND local_list_include system/src/stm/doc_ds_196/thirdparty/Src/system_stm32u0xx.c)
    list(APPEND local_list_include system/src/stm/doc_ds_196/thirdparty/Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_cortex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_196/thirdparty/Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_rcc.c)
    list(APPEND local_list_include system/src/stm/doc_ds_196/thirdparty/Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal_pwr_ex.c)
    list(APPEND local_list_include system/src/stm/doc_ds_196/thirdparty/Drivers/STM32U0xx_HAL_Driver/Src/stm32u0xx_hal.c)
endif()
