if(${MCU_NAME} MATCHES "^R5K574NCA4AE$|^R5K574NCA4BD$|^R5K574NCA4BG$|^R5K574NCB4AE$|^R5K574NCB4BD$|^R5K574NCB4BG$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.S PARENT_SCOPE)
    list(APPEND local_list_include system/src/${vendor}/r5k574ncab/init_clock.c system/src/${vendor}/r5k574ncab/vectors.c)
    list(APPEND local_dir_install system/src/${vendor}/r5k574ncab)
    set(${thirdpartyInstall} "r5k574ncab" PARENT_SCOPE)
endif()
