if(${MCU_NAME} MATCHES "^R5K574NCF4AE$|^R5K574NCF4BD$|^R5K574NCF4BG$|^R5K574NCF4FB$|^R5K574NCF4FC$|^R5K574NCF4FP$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.S PARENT_SCOPE)
    list(APPEND local_list_include system/src/${vendor}/r5k574ncf/init_clock.c system/src/${vendor}/r5k574ncf/vectors.c)
    list(APPEND local_dir_install system/src/${vendor}/r5k574ncf)
    set(${thirdpartyInstall} "r5k574ncf" PARENT_SCOPE)
endif()
