if(${MCU_NAME} MATCHES "^R5K574NCE4AE$|^R5K574NCE4BD$|^R5K574NCE4BG$|^R5K574NCE4FB$|^R5K574NCE4FC$|^R5K574NCE4FP$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.S PARENT_SCOPE)
    list(APPEND local_list_include system/src/${vendor}/r5k574nce/init_clock.c system/src/${vendor}/r5k574nce/vectors.c)
    list(APPEND local_dir_install system/src/${vendor}/r5k574nce)
    set(${thirdpartyInstall} "r5k574nce" PARENT_SCOPE)
endif()
