if(${MCU_NAME} MATCHES "^R5K574MCC4FB$|^R5K574MCC4FC$|^R5K574MCC4FP$|^R5K574MCD4FB$|^R5K574MCD4FC$|^R5K574MCD4FP$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.S PARENT_SCOPE)
    list(APPEND local_list_include system/src/${vendor}/r5k574mccd/init_clock.c system/src/${vendor}/r5k574mccd/vectors.c)
    list(APPEND local_dir_install system/src/${vendor}/r5k574mccd)
    set(${thirdpartyInstall} "r5k574mccd" PARENT_SCOPE)
endif()
