if(${MCU_NAME} MATCHES "^R5K574MCA4AE$|^R5K574MCA4BD$|^R5K574MCA4BG$|^R5K574MCB4AE$|^R5K574MCB4BD$|^R5K574MCB4BG$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.S PARENT_SCOPE)
    list(APPEND local_list_include system/src/${vendor}/r5k574mcab/init_clock.c system/src/${vendor}/r5k574mcab/vectors.c)
    list(APPEND local_dir_install system/src/${vendor}/r5k574mcab)
    set(${thirdpartyInstall} "r5k574mcab" PARENT_SCOPE)
endif()
