if(${MCU_NAME} MATCHES "^STM32U545CE$|^STM32U545JE$|^STM32U545NE$|^STM32U545RE$|^STM32U545VE$")
    set(uart_subimplementation "${CMAKE_CURRENT_LIST_DIR}/hal_ll_uart.c")
    set(rcc_subimplementation "${CMAKE_CURRENT_SOURCE_DIR}/../../include/rcc/implementations/doc_ds_179")
    set(gpio_subimplementation_include_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../include/gpio/implementations/doc_ds_179")
    list(APPEND hal_ll_def_list "STM32U5xx")
    list(APPEND hal_ll_def_list "STM32U54xx")
    list(APPEND hal_ll_def_list "STM32U545xx")
    set(uart_pin_map "${CMAKE_CURRENT_SOURCE_DIR}/../../include/uart/hal_ll_uart_pin_map/implementations/doc_ds_179")
endif()
