if(${MCU_NAME} MATCHES "^STM32U545CE$|^STM32U545JE$|^STM32U545NE$|^STM32U545RE$|^STM32U545VE$")
    set(adc_subimplementation "${CMAKE_CURRENT_LIST_DIR}/hal_ll_adc.c")
    set(rcc_subimplementation "${CMAKE_CURRENT_SOURCE_DIR}/../../include/rcc/implementations/doc_ds_179")
    set(gpio_subimplementation_include_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../include/gpio/implementations/doc_ds_179")
    list(APPEND hal_ll_def_list "STM32U5xx")
    list(APPEND hal_ll_def_list "STM32U54xx")
    list(APPEND hal_ll_def_list "STM32U545xx")
    set(adc_pin_map "${CMAKE_CURRENT_SOURCE_DIR}/../../include/adc/hal_ll_adc_pin_map/implementations/doc_ds_179")
    list(APPEND hal_ll_def_list "HAL_LL_ADC_RESOLUTION_CMAKE=HAL_LL_ADC_RESOLUTION_12_BIT")
endif()
