if(${MCU_NAME} MATCHES "^STM32H533CE$|^STM32H533HE$|^STM32H533RE$|^STM32H533VE$|^STM32H533ZE$")
    set(tim_subimplementation "${CMAKE_CURRENT_LIST_DIR}/hal_ll_tim.c")
    set(rcc_subimplementation "${CMAKE_CURRENT_SOURCE_DIR}/../../include/rcc/implementations/doc_ds_200")
    set(gpio_subimplementation_include_dir "${CMAKE_CURRENT_SOURCE_DIR}/../../include/gpio/implementations/doc_ds_200")
    list(APPEND hal_ll_def_list "STM32H5xx")
    list(APPEND hal_ll_def_list "STM32H53xx")
    list(APPEND hal_ll_def_list "STM32H533xx")
    set(tim_pin_map "${CMAKE_CURRENT_SOURCE_DIR}/../../include/tim/hal_ll_tim_pin_map/implementations/doc_ds_200")
endif()
