name: Verify NECTO and Package Assets

on:
  workflow_dispatch:

  schedule:
    - cron: "0 4 * * 1-5"   # 06:00, Monday–Friday
    - cron: "0 9 * * 1-5"   # 11:00, Monday–Friday
    - cron: "0 13 * * 1-5"  # 15:00, Monday–Friday

jobs:
  # Install NECTO on different OSs (runs in parallel via matrix)
  necto_verification:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ubuntu runtime deps
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1 \
            libgl1 \
            libgbm1 \
            libxkbcommon0 \
            libxkbcommon-x11-0 \
            libxcb-cursor0 \
            libxcb-xinerama0 \
            libnss3 \
            libasound2 \
            libminizip1
          echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements/check_necto_links.txt

      - name: Verify NECTO installation
        run: |
          python -u scripts/install_necto.py ${{ matrix.os }}

  # Verify packages (runs in parallel after build passes)
#   packages_verification:
#     needs: necto_verification
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         packages: [bsp_packages, mchp_programmers, core_packages, codegrip_packages]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.x'

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r scripts/requirements/check_necto_links.txt

#       - name: Verify packages
#         run: |
#           python -u scripts/check_necto_packages.py ${{ matrix.packages }}
