name: SDK Recursive Build

on:
  workflow_dispatch:

jobs:
  recursiveBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp
          pip install aiofiles
          pip install requests
          pip install py7zr
          pip install elasticsearch==7.13.4
          sudo apt-get install p7zip-full
          sudo apt-get install ffmpeg libsm6 libxext6  -y

      - name: Install NECTO
        run: |
          bash scripts/installNecto.sh

      - name: Run Recursive Build
        run: |
          echo "----- Let's see our location. --------"
          pwd
          echo "----- Let's see what we have here. -----"
          ls -la
          python -u scripts/recursive_build.py
