name: SDK Recursive Build

on:
  workflow_dispatch:

jobs:
  recursiveBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp
          pip install aiofiles
          pip install requests
          pip install py7zr
          pip install elasticsearch==7.13.4
          sudo apt-get install p7zip-full
          sudo apt-get install freeglut3-dev
          sudo apt-get install libevent-dev
          sudo apt-get install libopus-dev
          sudo apt-get install libminizip-dev
          sudo apt-get install libxkbcommon-x11-dev
          sudo apt-get install libxcb-cursor0
          sudo apt-get install libxcb-xinerama0
          sudo apt-get install libxcb-icccm4
          sudo apt-get install libxcb-keysyms1
          sudo apt-get install libxcb-render-util0
          sudo apt-get install libxcb-shape
          sudo apt-get install libxcb-randr
          sudo apt-get install libxcb-xfixes
          sudo apt-get install libxcb-xkb
          sudo apt-get install libxcb-sync
          sudo apt-get install libxcb-shm
          sudo apt-get install libxcb-image
          sudo apt-get install libxcb-util
          export PATH=$PATH:~/Qt/Tools/QtCreator/bin

      - name: Install NECTO
        run: |
          bash scripts/installNecto.sh

      - name: Run Recursive Build
        run: |
          export QT_DEBUG_PLUGINS=1
          cd /home/runner/work/SDK-Build-Tool/SDK-Build-Tool
          git pull
          git diff origin/main > gitDiff.txt
          cd /home/runner/work/SDK-Build-Tool/.MIKROE/NECTOStudio7/packages/sdk/2.11.1/src
          rm -rf /home/runner/work/SDK-Build-Tool/.MIKROE/NECTOStudio7/packages/sdk/2.11.1/src/*
          cd /home/runner/work/SDK-Build-Tool/SDK-Build-Tool
          shopt -s extglob
          cp -r !(.git|.github|scripts|templates) /home/runner/work/SDK-Build-Tool/.MIKROE/NECTOStudio7/packages/sdk/2.11.1/src/
          cd /home/runner/work/SDK-Build-Tool/MikroElektronika/NECTOStudio/bin
          echo "Running sdk_build_automation"
          ./sdk_build_automation --compiler "mikrocavr" --sdk "mikrosdk_v2111" --installPrefix "/home/runner/work/SDK-Build-Tool/build_test"
