name: SDK Recursive Build

on:
  workflow_dispatch:

jobs:
  recursiveBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp
          pip install aiofiles
          pip install requests
          pip install py7zr
          pip install elasticsearch==7.13.4
          sudo apt-get install p7zip-full
          sudo apt-get install freeglut3-dev

      - name: Install NECTO
        run: |
          bash scripts/installNecto.sh

      - name: Run Recursive Build
        run: |
          echo "----- Let's replace installed SDK contents with current SDK for testing. --------"
          echo "Original contents of SDK:"
          cd /home/runner/work/SDK-Build-Tool/.MIKROE/NECTOStudio7/packages/sdk/2.11.1/src
          ls -la
          rm -rf /home/runner/work/SDK-Build-Tool/.MIKROE/NECTOStudio7/packages/sdk/2.11.1/src/*
          echo "Removed files, so it should be empty:"
          ls -la
          cd /home/runner/work/SDK-Build-Tool/SDK-Build-Tool
          cp -r !(.git|.github|scripts|templates) /home/runner/work/SDK-Build-Tool/.MIKROE/NECTOStudio7/packages/sdk/2.11.1/src/
          cd /home/runner/work/SDK-Build-Tool/.MIKROE/NECTOStudio7/packages/sdk/2.11.1/src
          echo "Copied contents of SDK:"
          ls -la
