name: SDK Recursive Build

on:
  workflow_dispatch:
    inputs:
        build_type:
          type: choice
          description: Build all or only changed files
          options:
            - Only changed files
            - All files


jobs:
  recursiveBuild:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp
          pip install aiofiles
          pip install requests
          pip install py7zr
          pip install elasticsearch==7.13.4
          sudo apt-get update
          sudo apt-get install p7zip-full
          sudo apt-get install freeglut3-dev
          sudo apt-get install libevent-dev
          sudo apt-get install libopus-dev
          sudo apt-get install libminizip-dev
          sudo apt-get install libfontconfig1-dev
          sudo apt-get install libfreetype-dev
          sudo apt-get install libx11-dev
          sudo apt-get install libx11-xcb-dev
          sudo apt-get install libxext-dev
          sudo apt-get install libxfixes-dev
          sudo apt-get install libxi-dev
          sudo apt-get install libxrender-dev
          sudo apt-get install libxcb1-dev
          sudo apt-get install libxcb-cursor-dev
          sudo apt-get install libxcb-glx0-dev
          sudo apt-get install libxcb-keysyms1-dev
          sudo apt-get install libxcb-image0-dev
          sudo apt-get install libxcb-shm0-dev
          sudo apt-get install libxcb-icccm4-dev
          sudo apt-get install libxcb-sync-dev
          sudo apt-get install libxcb-xfixes0-dev
          sudo apt-get install libxcb-shape0-dev
          sudo apt-get install libxcb-randr0-dev
          sudo apt-get install libxcb-render-util0-dev
          sudo apt-get install libxcb-util-dev
          sudo apt-get install libxcb-xinerama0-dev
          sudo apt-get install libxcb-xkb-dev
          sudo apt-get install libxkbcommon-dev
          sudo apt-get install libxkbcommon-x11-dev

      - name: Install NECTO
        run: |
          python -u scripts/install_necto.py

      - name: Recursive Build for all files
        if: "${{ github.event.inputs.build_type == 'All files'}}"
        run: |
          export BUILD_ALL=1
          echo "Building all files."
          python -u scripts/recursive_build.py

      - name: Recursive build only for changed files 
        if: "${{ github.event.inputs.build_type == 'Only changed files'}}"
        run: |
          rm -rf /home/runner/.MIKROE/NECTOStudio7/packages/sdk/2.11.1/src/*
          cd /home/runner/work/SDK-Build-Tool/SDK-Build-Tool
          shopt -s extglob
          cp -r !(.git|.github|scripts|templates) /home/runner/.MIKROE/NECTOStudio7/packages/sdk/2.11.1/src/
          export BUILD_ALL=0
          echo "Building only changed files."
          python -u scripts/recursive_build.py

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: /home/runner/test_results
